### ISSUE TITLE
low power with XTAL on esp32/C3

### ISSUE THREAD

**Issue by chegewara** [chegewara/arduino-esp32-c3-xtal#1]
In this post we have all instruction how to enable XTAL 32kHz low power with BLE:
https://github.com/espressif/esp-idf/issues/947#issuecomment-500312453

In addition this can be added:
```
#include "esp_err.h"
#include "esp_pm.h"

  esp_pm_config_esp32c3_t pm_config = {
    .max_freq_mhz = 160, // e.g. 80, 160, 240
    .min_freq_mhz = 80, // e.g. 40
    .light_sleep_enable = true, // enable light sleep
  };
  ESP_ERROR_CHECK_WITHOUT_ABORT( esp_pm_configure(&pm_config) );

```

Its confirmed it is working very good with arduino as well, using this repository, which is based on esp-idf 4.4.3 and arduino-esp32 2.0.5 or so.

**Comment by chegewara** [comment]
Add this to [defconfig](https://github.com/espressif/esp32-arduino-lib-builder/blob/master/configs/defconfig.esp32c3)
```
CONFIG_ESP32C3_RTC_CLK_SRC_EXT_CRYS=y
CONFIG_ESP32C3_RTC_CLK_SRC=y
CONFIG_BT_CTRL_MODEM_SLEEP=y
CONFIG_BT_CTRL_MODEM_SLEEP_MODE_1=y
CONFIG_BT_CTRL_LPCLK_SEL_EXT_32K_XTAL=y
CONFIG_PM_ENABLE=y
CONFIG_PM_DFS_INIT_AUTO=y
CONFIG_FREERTOS_USE_TICKLESS_IDLE=y
```

**Comment by nilp0inter** [comment]
I am trying to figure out how to use this repository with Arduino IDE.  Could you give me some instructions or recommend some guide?

Cheers.

**Comment by chegewara** [comment]
I didnt try it with arduino IDE, just platformio, but i am guessing you could replace installation folder with this repository.

**Comment by nilp0inter** [comment]
I migrated my project to platformio in order to use this library, but I cannot figure out how to use it.  Could you provide an example `platformio.ini`?

Thank you!

**Comment by chegewara** [comment]
Sorry, but this configuration has been prepared for commercial project and i am not going to support "how to" in here.
It can be easy used as any other platformio project with esp32C3.

```
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions.csv
platform = https://github.com/platformio/platform-espressif32.git#v5.2.0
platform_packages =
  framework-arduinoespressif32 @ https://github.com/chegewara/arduino-esp32-c3-xtal
lib_deps = 
  h2zero/NimBLE-Arduino@^1.4.0
```

**Comment by nilp0inter** [comment]
I understand. Thank you for sharing 👍
